# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: custom-acl
destinationName: custom-acl
sourceName: custom-acl
action: deny